name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Run ESLint
        run: |
          cd client
          npm run lint

#       - name: Run tests
#         run: npm test
#         env:
#           JWT_SECRET: ${{ secrets.JWT_SECRET }}
